# Generated by Django 2.2.7 on 2019-12-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_auto_20191121_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nivelEstudios',
            field=models.CharField(choices=[('1', 'Primaria'), ('2', 'Secundaria'), ('3', 'Bachillerato'), ('4', 'Licenciatura'), ('5', 'Especialidad'), ('6', 'Maestria'), ('7', 'Doctorado'), ('8', 'Post-Doctorado')], max_length=1),
        ),
    ]
