# Generated by Django 2.2.7 on 2019-12-10 15:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_auto_20191202_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='edad',
            field=models.IntegerField(validators=[django.core.validators.validate_integer]),
        ),
    ]
