# Generated by Django 2.2.7 on 2019-12-13 01:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_auto_20191211_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='edad',
            field=models.CharField(max_length=2, validators=[django.core.validators.validate_integer]),
        ),
    ]
