# Generated by Django 2.2.7 on 2019-11-21 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0002_auto_20191121_1424'),
        ('areamaestro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.Persona')),
                ('cubiculo', models.CharField(max_length=50)),
                ('numeroTrabajador', models.CharField(max_length=13)),
                ('estatus', models.CharField(choices=[('A', 'Activo'), ('ST', 'Suspendido'), ('P', 'Permiso'), ('SD', 'Suspendido Definitivo')], max_length=2)),
                ('areamaestro', models.ForeignKey(help_text='Seleccione un Área', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maestroAreaExpertise', to='areamaestro.AreaMaestro')),
            ],
            bases=('personas.persona',),
        ),
    ]
