# Generated by Django 2.2.7 on 2019-12-02 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_estudiante_materias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='materias',
        ),
    ]
