# Generated by Django 2.2.7 on 2019-12-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
        ('estudiantes', '0004_remove_estudiante_materias'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='materias',
            field=models.ManyToManyField(null=True, related_name='estudianteMateria', to='materias.Materia'),
        ),
    ]
