# Generated by Django 2.2.7 on 2019-12-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0005_estudiante_materias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='materias',
            field=models.ManyToManyField(related_name='estudianteMateria', to='materias.Materia'),
        ),
    ]
