# Generated by Django 2.2.7 on 2019-12-11 13:51

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0006_auto_20191202_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='matricula',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='numeroMateriasCursando',
            field=models.CharField(max_length=2, validators=[django.core.validators.validate_integer]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='totalNumeroMateriasAprobadas',
            field=models.CharField(default=0, max_length=2, validators=[django.core.validators.validate_integer]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='totalNumerosMateriasReprobadas',
            field=models.CharField(default=0, max_length=2, validators=[django.core.validators.validate_integer]),
        ),
    ]
