# Generated by Django 2.2.7 on 2019-11-21 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0005_auto_20191121_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='maestroasignado',
            field=models.ForeignKey(help_text='Seleccione un Maestro', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gruposmaestroasignado', to='maestros.Maestro'),
        ),
    ]
