# Generated by Django 2.2.7 on 2019-12-02 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0006_auto_20191121_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='maestroasignado',
        ),
    ]
