# Generated by Django 2.2.7 on 2019-12-11 13:51

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0008_grupo_maestroasignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='nombre',
            field=models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')]),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='numeroAlumnos',
            field=models.IntegerField(validators=[django.core.validators.validate_integer]),
        ),
    ]
