# Generated by Django 2.2.7 on 2019-12-11 13:51

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('areaestudiomateria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaestudiomateria',
            name='area',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')]),
        ),
    ]
