# Generated by Django 2.2.7 on 2019-12-13 22:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0006_auto_20191213_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.Persona')),
                ('numeroAdministrativo', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')])),
                ('numeroOficina', models.CharField(max_length=3, validators=[django.core.validators.validate_integer])),
            ],
            bases=('personas.persona',),
        ),
    ]
